title: Your awesome title
author: Vsevolod
email: vsevolod@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Some placeholder

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
